language: cpp
os: osx
compiler: clang
script:
  - git clone --recursive https://github.com/uNetworking/uWebSockets.js.git
  - cd uWebSockets.js
  - make
  - git checkout binaries
  - cp dist/*.node .
  - git status
  - git pull origin binaries
  - git commit -a -m "[TravisCI] Updated macOS binaries" --allow-empty
  - git push "https://alexhultman:$SECRET@github.com/uNetworking/uWebSockets.js" binaries
